apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trigger-rally
spec:
  destination:
    namespace: triggerrally
    server: http://kubernetes.default.svc
  source:
    path: /
    repoURL: git@github.com:benoit-planche/testgitops.git
    targetRevision: HEAD
  sources: []
  project: gitops