apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trigger-rally
spec:
  destination:
    namespace: triggerrally
    server: https://kubernetes.default.svc
  source:
    path: /
    repoURL: https://github.com/benoit-planche/testgitops.git
    targetRevision: HEAD
  sources: []
  project: gitops